### PR TITLE
First stab at a Webpack based build

### PR DESCRIPTION
**Pull request by bebraw**
This is based on [react-component-boilerplate](https://github.com/survivejs/react-component-boilerplate). Following features are provided:

* Webpack driven build/development mode with hot loading. Hit `npm start` to access the dev mode. `npm run dist` to generate builds
* In addition source build is generated for Node through Babel
* Linting is provided through ESlint - `npm run lint`
* GitHub Pages support - `npm run gh-pages` + `npm run deploy-gh-pages`
* `npm run version x.x.x` for generating versions with dist build etc.
automatically

I didn't touch the test configuration. You will have to tweak the demo and branding to your liking.

### CODE REVIEW

**Comment by bebraw** [comment]
Note that things like `jscs` style can be added easily to the build if you want. Also more linting rules can be enabled at `.eslintrc`. I disabled a couple of the default ones.

**Comment by bebraw** [comment]
What if we used something like [component playground](http://projects.formidablelabs.com/component-playground/) for interactive examples at the demo site? I haven't used that on my projects yet but it seems like it could fit this project well.

**Comment by PaulLeCam** [comment]
Hi,

Thanks for the PR but that seems quite overkill for this kind of project.

The development/release workflow is quite simple as it is and I don't want to add a dependency on Webpack as IMO it's up to the application to handle how it packages the modules, not the library to impose specific implementations.

**Comment by bebraw** [comment]
The implementation doesn't tie possible applications to Webpack in any manner. It is strictly for development.

The Node version remains the same. There is an UMDified version that can be easily consumed from global, CommonJS or AMD environment making it actually easier to consume the library.

**Comment by PaulLeCam** [comment]
Hey, OK I'll have a look when I have time, thanks!

**Comment by bebraw** [comment]
I see you integrated webpack already. It's safe to close this. Note that the [boilerplate](https://github.com/survivejs/react-component-boilerplate) has evolved somewhat. Perhaps you can pick up a trick or two from there.

**Pull request closed without merging**
